#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamweDev_GP_Service
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database1")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertProduct(Product instance);
    partial void UpdateProduct(Product instance);
    partial void DeleteProduct(Product instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Database1ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<Product> Products
		{
			get
			{
				return this.GetTable<Product>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[User]")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private string _Surname;
		
		private string _Email;
		
		private string _Password;
		
		private string _UserType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnSurnameChanging(string value);
    partial void OnSurnameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnUserTypeChanging(string value);
    partial void OnUserTypeChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this.OnSurnameChanging(value);
					this.SendPropertyChanging();
					this._Surname = value;
					this.SendPropertyChanged("Surname");
					this.OnSurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserType", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string UserType
		{
			get
			{
				return this._UserType;
			}
			set
			{
				if ((this._UserType != value))
				{
					this.OnUserTypeChanging(value);
					this.SendPropertyChanging();
					this._UserType = value;
					this.SendPropertyChanged("UserType");
					this.OnUserTypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Product")]
	public partial class Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _PrName;
		
		private string _PrDescription;
		
		private string _PrCategory;
		
		private int _PrRating;
		
		private int _PrQuantity;
		
		private decimal _PrPrice;
		
		private System.Nullable<decimal> _PrOldPrice;
		
		private string _PrStatus;
		
		private string _PrImage;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnPrNameChanging(string value);
    partial void OnPrNameChanged();
    partial void OnPrDescriptionChanging(string value);
    partial void OnPrDescriptionChanged();
    partial void OnPrCategoryChanging(string value);
    partial void OnPrCategoryChanged();
    partial void OnPrRatingChanging(int value);
    partial void OnPrRatingChanged();
    partial void OnPrQuantityChanging(int value);
    partial void OnPrQuantityChanged();
    partial void OnPrPriceChanging(decimal value);
    partial void OnPrPriceChanged();
    partial void OnPrOldPriceChanging(System.Nullable<decimal> value);
    partial void OnPrOldPriceChanged();
    partial void OnPrStatusChanging(string value);
    partial void OnPrStatusChanged();
    partial void OnPrImageChanging(string value);
    partial void OnPrImageChanged();
    #endregion
		
		public Product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PrName
		{
			get
			{
				return this._PrName;
			}
			set
			{
				if ((this._PrName != value))
				{
					this.OnPrNameChanging(value);
					this.SendPropertyChanging();
					this._PrName = value;
					this.SendPropertyChanged("PrName");
					this.OnPrNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrDescription", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string PrDescription
		{
			get
			{
				return this._PrDescription;
			}
			set
			{
				if ((this._PrDescription != value))
				{
					this.OnPrDescriptionChanging(value);
					this.SendPropertyChanging();
					this._PrDescription = value;
					this.SendPropertyChanged("PrDescription");
					this.OnPrDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrCategory", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PrCategory
		{
			get
			{
				return this._PrCategory;
			}
			set
			{
				if ((this._PrCategory != value))
				{
					this.OnPrCategoryChanging(value);
					this.SendPropertyChanging();
					this._PrCategory = value;
					this.SendPropertyChanged("PrCategory");
					this.OnPrCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrRating", DbType="Int NOT NULL")]
		public int PrRating
		{
			get
			{
				return this._PrRating;
			}
			set
			{
				if ((this._PrRating != value))
				{
					this.OnPrRatingChanging(value);
					this.SendPropertyChanging();
					this._PrRating = value;
					this.SendPropertyChanged("PrRating");
					this.OnPrRatingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrQuantity", DbType="Int NOT NULL")]
		public int PrQuantity
		{
			get
			{
				return this._PrQuantity;
			}
			set
			{
				if ((this._PrQuantity != value))
				{
					this.OnPrQuantityChanging(value);
					this.SendPropertyChanging();
					this._PrQuantity = value;
					this.SendPropertyChanged("PrQuantity");
					this.OnPrQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrPrice", DbType="Money NOT NULL")]
		public decimal PrPrice
		{
			get
			{
				return this._PrPrice;
			}
			set
			{
				if ((this._PrPrice != value))
				{
					this.OnPrPriceChanging(value);
					this.SendPropertyChanging();
					this._PrPrice = value;
					this.SendPropertyChanged("PrPrice");
					this.OnPrPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrOldPrice", DbType="Money")]
		public System.Nullable<decimal> PrOldPrice
		{
			get
			{
				return this._PrOldPrice;
			}
			set
			{
				if ((this._PrOldPrice != value))
				{
					this.OnPrOldPriceChanging(value);
					this.SendPropertyChanging();
					this._PrOldPrice = value;
					this.SendPropertyChanged("PrOldPrice");
					this.OnPrOldPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrStatus", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string PrStatus
		{
			get
			{
				return this._PrStatus;
			}
			set
			{
				if ((this._PrStatus != value))
				{
					this.OnPrStatusChanging(value);
					this.SendPropertyChanging();
					this._PrStatus = value;
					this.SendPropertyChanged("PrStatus");
					this.OnPrStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrImage", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string PrImage
		{
			get
			{
				return this._PrImage;
			}
			set
			{
				if ((this._PrImage != value))
				{
					this.OnPrImageChanging(value);
					this.SendPropertyChanging();
					this._PrImage = value;
					this.SendPropertyChanged("PrImage");
					this.OnPrImageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
